"use client";

import {useEffect,useState} from "react";

type Report={days:number;summary:{sessions?:number;page_views?:number;video_opens?:number;watch_seconds?:number};topVideos:Array<{video_id:string;opens:number;watch_seconds:number}>;sources:Array<{name:string;sessions:number}>;countries:Array<{name:string;sessions:number}>;devices:Array<{name:string;sessions:number}>;events:Array<{name:string;count:number}>;recent:Array<{created_at:string;session_id:string;event_name:string;path:string;video_id:string;referrer_host:string;country:string;city:string;device:string;browser:string;properties:Record<string,unknown>}>};

function duration(value:number){const s=Math.max(0,Math.round(Number(value)||0));const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h?`${h}ω ${m}λ`:`${m} λεπτά`;}

export default function AnalyticsPage(){
  const [days,setDays]=useState(7);const [report,setReport]=useState<Report|null>(null);const [error,setError]=useState("");
  useEffect(()=>{setReport(null);setError("");void fetch(`/api/analytics/report?days=${days}`,{cache:"no-store",credentials:"same-origin"}).then(async r=>{if(r.status===401)throw new Error("Χρειάζεται πρώτα admin login από το GreekTube Subs.");if(!r.ok)throw new Error("Δεν φορτώθηκαν τα analytics.");setReport(await r.json());}).catch(e=>setError(e instanceof Error?e.message:"Error"));},[days]);
  return <main className="analytics-page"><header><div><span>GREEKTUBE SUBS</span><h1>Analytics</h1><p>First-party traffic και product usage χωρίς raw IP.</p></div><a href="/">← Πίσω στο site</a></header><nav>{[1,7,30,90].map(value=><button key={value} className={days===value?"active":""} onClick={()=>setDays(value)}>{value===1?"Σήμερα":`${value} ημέρες`}</button>)}</nav>{error?<section className="message">{error}</section>:!report?<section className="message">Φόρτωση…</section>:<><section className="metrics"><article><small>SESSIONS</small><strong>{report.summary.sessions||0}</strong></article><article><small>PAGE VIEWS</small><strong>{report.summary.page_views||0}</strong></article><article><small>VIDEO OPENS</small><strong>{report.summary.video_opens||0}</strong></article><article><small>WATCH TIME</small><strong>{duration(report.summary.watch_seconds||0)}</strong></article></section><section className="grid"><Panel title="Top videos">{report.topVideos.length?report.topVideos.map(v=><Row key={v.video_id} name={v.video_id} value={`${v.opens} ανοίγματα · ${duration(v.watch_seconds)}`}/>):<Empty/>}</Panel><Panel title="Traffic sources">{report.sources.length?report.sources.map(v=><Row key={v.name} name={v.name||"direct"} value={`${v.sessions}`}/>):<Empty/>}</Panel><Panel title="Χώρες">{report.countries.length?report.countries.map(v=><Row key={v.name} name={v.name} value={`${v.sessions}`}/>):<Empty/>}</Panel><Panel title="Συσκευές">{report.devices.length?report.devices.map(v=><Row key={v.name} name={v.name||"Other"} value={`${v.sessions}`}/>):<Empty/>}</Panel></section><section className="recent"><div className="section-head"><div><span>LIVE EVENT FEED</span><h2>Τελευταίες ενέργειες</h2></div><strong>{report.recent.length}</strong></div><div className="table"><div className="tr head"><span>Ώρα</span><span>Event</span><span>Video / Page</span><span>Location</span><span>Device</span></div>{report.recent.map((e,i)=><div className="tr" key={`${e.created_at}-${i}`}><span>{new Date(e.created_at).toLocaleString("el-GR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}</span><span>{e.event_name}</span><span>{e.video_id||e.path}</span><span>{[e.city,e.country].filter(Boolean).join(", ")||"—"}</span><span>{e.device} · {e.browser}</span></div>)}</div></section></>}<style>{styles}</style></main>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><h2>{title}</h2><div>{children}</div></section>}
function Row({name,value}:{name:string;value:string}){return <div className="row"><span>{name}</span><strong>{value}</strong></div>}
function Empty(){return <p className="empty">Δεν υπάρχουν ακόμη δεδομένα.</p>}
const styles=`
*{box-sizing:border-box}.analytics-page{min-height:100vh;padding:32px clamp(16px,4vw,56px) 80px;background:#090b0f;color:#f4f4f1;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.analytics-page>header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;max-width:1480px;margin:0 auto}.analytics-page header span,.section-head span{color:#8f83ed;font-size:8px;font-weight:760;letter-spacing:.14em}.analytics-page h1{margin:5px 0 4px;font-size:30px;letter-spacing:-.04em}.analytics-page header p{margin:0;color:#858b95;font-size:11px}.analytics-page header a{color:#aaa1ef;text-decoration:none;font-size:10px}.analytics-page>nav{max-width:1480px;margin:24px auto 14px;display:flex;gap:7px}.analytics-page nav button{height:34px;padding:0 11px;border:1px solid rgba(255,255,255,.09);border-radius:9px;background:#12161c;color:#8f959f;font-size:9px}.analytics-page nav button.active{border-color:rgba(143,127,240,.42);background:rgba(143,127,240,.12);color:#ddd8ff}.metrics,.grid,.recent,.message{max-width:1480px;margin-left:auto;margin-right:auto}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.metrics article,.panel,.recent,.message{border:1px solid rgba(255,255,255,.075);border-radius:15px;background:#101319}.metrics article{padding:16px}.metrics small{display:block;color:#737a85;font-size:7.5px;font-weight:760;letter-spacing:.1em}.metrics strong{display:block;margin-top:7px;font-size:22px;letter-spacing:-.035em}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:10px}.panel{padding:15px}.panel h2,.section-head h2{margin:0 0 11px;font-size:13px;font-weight:650}.row{display:flex;justify-content:space-between;gap:15px;padding:8px 0;border-top:1px solid rgba(255,255,255,.055);font-size:10px}.row span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#a7acb4}.row strong{color:#777f8b;font-size:9px;font-weight:580}.empty{color:#6e7580;font-size:10px}.recent{margin-top:10px;padding:15px}.section-head{display:flex;align-items:flex-start;justify-content:space-between}.section-head h2{margin-top:4px}.section-head>strong{color:#888f9a;font-size:9px}.table{overflow:auto}.tr{min-width:820px;display:grid;grid-template-columns:120px 120px minmax(220px,1fr) 160px 170px;gap:12px;padding:8px 3px;border-top:1px solid rgba(255,255,255,.05);color:#9da3ad;font-size:9.5px}.tr.head{color:#666e79;font-size:8px;font-weight:720;letter-spacing:.06em}.message{padding:24px;color:#8f959f;font-size:11px}@media(max-width:760px){.analytics-page{padding:20px 12px 60px}.analytics-page h1{font-size:24px}.metrics{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.metrics strong{font-size:18px}}
`;
